### ISSUE TITLE
FLAIR analysis of 3 conditions

### ISSUE THREAD

**Issue by drc111** [BrooksLabUCSC/flair#108]
Hi,

For running FLAIR on samples from 3 different conditions (each with 3 replicates),
would you suggest to i) run FLAIR-collapse, quantify, and diffExp on the conditions pairwise or ii) concatenate all conditions before FLAIR-collapse followed by running FLAIR-quantify/diffExp on the conditions pairwise afterwards?

Since I am interested in isoforms expression/usage, I am also specifying the '-n best_only' flag in FLAIR-collapse - I thus assume that it might be safer to collapse isoforms for the conditions pairwise (i), since TSS/TTS for an isoform might be chosen differently depending on the conditions and thus mess with isoform quantification/diffExp downstream.

Thanks!
Sebastian

**Comment by belgravia** [comment]
Hi Sebastian,

I would typically recommend doing it the second way just so that the isoforms are collapse with the most amount of information. I think that for your case, your point of using the best_only flag and wanting to look at TSS/TTS that are determined 'best' for the pair makes sense, and doing it the first way would be ok. I would just also note that the 'best' TSS/TTS is just whichever end site has the most support; if you have different sequencing depths of your conditions, whichever condition is sequenced most deeply would drive TSS/TTS determination with the best_only flag on.

-Alison

**Comment by drc111** [comment]
Hi Alison,

Thanks for the quick reply.
I am mainly using the 'best' flag to make FLAIR only assemble one isoform per unique splice junction and I am not specifically interested in TSS/TTS sites. 
I am mainly following the approach from your paper from March from which I understand that you concatenated all CLL WT, CLL mut and B samples prior to FLAIR-collapse?
Just to be clear, would you suggest to concatenate all conditions prior to FLAIR-collapse if I am mainly interested in isoform expression/usage? 

Thanks for your time,
Sebastian

**Comment by belgravia** [comment]
Yes, I concatenated all the samples prior to running FLAIR-collapse. If you are interested in isoform expression/usage, then concatenating beforehand would make comparisons between all of your groups easier. The quantify and diffexp step will determine the expression of each isoform in each of your samples and then compare isoform expression between two groups. If you split up your samples to do some sort of pairwise runs of collapse, it would be less convenient for you to compare between samples mainly because the novel isoforms will have different names and TSS/TES may be slightly different.
-Alison

**Comment by drc111** [comment]
Thanks a lot!
