### ISSUE TITLE
some problems in collapse step

### ISSUE THREAD

**Issue by y842739756** [BrooksLabUCSC/flair#113]
collapse usage said that :
"

> For the gene field, the gene that is assigned to the isoform is based on whichever annotated gene has the greatest number of splice junctions shared with the isoform. If there are no genes in the annotation which can be assigned to the isoform, a genomic coordinate is used

"
But in my case ,their still some isoforms share the splice junctions with annotated gene,but still cluster as a genomic coordinate describe gene like :

`RcHm_v2.0_Chr5	5830216	5831929	mRNA:RcHm_v2.0_Chr5g0008871_gene:RcHm_v2.0_Chr5g0008871	60	+	5830216	5831929	27,158,119	410,348,	0,1365,`
`RcHm_v2.0_Chr5	5830216	5831929	34e49db7-ca33-4c39-ab66-e0d0de34136f_RcHm_v2.0_Chr5:5830000	60	+	5830216	5831929	27,158,119	2	412,348,	0,1365,`
these two isoforms in same locus with only 2bp difference in 1st exon ,and cluster as two different genes,that make me confused .
how could I handle this problem,please help me 
Thanks 
best wishes

**Comment by belgravia** [comment]
They cluster as two different genes because the second isoform has a unique splice junction that is not in an annotated gene. FLAIR is associating the isoforms to known genes by exact intron matches. You could intersect your annotation with the flair isoforms to cluster genes by their general loci. E.g. you could convert your annotation gtf to bed (there's a gtf_to_bed.py script in the flair bin) and then use bedtools intersect. You will then just have to resolve cases where there are overlapping genes in the annotation at a certain locus. Hope that helps. 
-Alison

**Comment by y842739756** [comment]
Thanks , this answer help me a lot.


Best Wishes
XU




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Alison"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月16日(星期二) 上午8:31
收件人:&nbsp;"BrooksLabUCSC/flair"<flair@noreply.github.com&gt;;
抄送:&nbsp;"IANMOONE"<842739756@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [BrooksLabUCSC/flair] some problems in collapse step (#113)





 
They cluster as two different genes because the second isoform has a unique splice junction that is not in an annotated gene. FLAIR is associating the isoforms to known genes by exact intron matches. You could intersect your annotation with the flair isoforms to cluster genes by their general loci. E.g. you could convert your annotation gtf to bed (there's a gtf_to_bed.py script in the flair bin) and then use bedtools intersect. You will then just have to resolve cases where there are overlapping genes in the annotation at a certain locus. Hope that helps.
 -Alison
