### ISSUE TITLE
flair.collapse.isoforms.fa strandness

### ISSUE THREAD

**Issue by robinycfang** [BrooksLabUCSC/flair#115]
Hi,

Just wondering what is the strandness of the transcript sequence in flair.collapse.isoforms.fa? Is all the sequence presented as + strand from the reference genome? Or the sequence is already presented on the strand that it actually belongs to? Need a confirmation on the strandness, as my downstream analysis will depend specifically on the strandness. Thanks!

ps: I am using nanopore direct RNA seq without PCR, so if I understand correctly, the reads and seuence I get are from their actual strand? 

YC

**Comment by belgravia** [comment]
The isoform sequences should correspond to the strand the isoform belongs to. 
I addressed this at the bottom of your issue #70 .
Let me know if there are any problems!
-Alison

**Comment by robinycfang** [comment]
@belgravia Thanks again for your answer Alison!
The reason why I asked again to confirm is because I picked a novel isoform which is annotated to be on the reverse strand in flair.collapse.isoforms.gtf. I compare its sequence taken from flair.collapse.isoforms.fa to the reference genome fa file (all sequences are presented as forward stand), and found that the novel isoform sequence is actually on the forward strand. I am using FLAIR v1.4.

**Comment by belgravia** [comment]
Yes in the v1.4 release, it reports everything in the forward strand. If you have cloned the flair repository and kept updated with commits, then the strand issue should have been fixed many months ago when you first brought it up. If you are using docker or the conda package, then I would recommend updating to the v1.5 release so that the strandedness can be correct for you.
-Alison
