### ISSUE TITLE
Incorporating terminal site data?

### ISSUE THREAD

**Issue by abs-yy** [BrooksLabUCSC/flair#119]
Hi,

Since flair is TSS-aware, would it be possible for it to be TTS-aware as well?
Sometimes I get two transcripts with same exon structures but has slightly different TTS. I have access to 3'end sequencing data, so if I can provide this to flair collapse like the promoter option it might make more better gene models. 
Additionally, would it be possible to classify regions after a stop codon as the 3'UTR in the collapse output ?

Thanks!

**Comment by belgravia** [comment]
Hi,

> Since flair is TSS-aware, would it be possible for it to be TTS-aware as well?

Since I had the promoter file argument in place, it was easy to add one for 3' end data. If you can try the latest commit, you can use `--3prime_regions` to specify the name of your 3' file. Let me know if you have a better suggestion for this parameter name. 

> Additionally, would it be possible to classify regions after a stop codon as the 3'UTR in the collapse output ?

I think for now I will keep UTR determination out of the collapse step. You can run the predictProductivity.py script or some other software that predicts the coding frame for isoforms. The bed file from predictProductivity from can be converted to gtf using `psl_to_gtf.py` (which works with bed files too) and then your gtf will contain UTR regions. 

-Alison

**Comment by abs-yy** [comment]
Hi Alison,

Thanks for the quick change!

I've tried the --3prime_regions option with my 3'end-sequence data, but there result has has several transcripts missing that had strong 3' support. I can't figure out the reason for this, do you have any ideas?

I also tried the predictProductivity.py and psl_to_gtf.py, and noticed the following.
1) predictProductivity.py can not use the flair collapse output gtf, it requires start_codon/stop_codon rows (and is also missing gene rows). Can psl_to_gtf.py output these rows as well?
2) CDS/exon regions that were annotated as UTRs were still left in the output. Noticed this during Jbrowse visualization.

**Comment by belgravia** [comment]
Hi,

Thanks for trying it out. Sorry I pushed too fast and realized that it was still filtering on start positions. I have made a new commit with the fixes. Please try again!

For predictProductivity, you are supposed to give it a reference annotation with start_codon fields and flair will use those start codons to predict the reading frame of the isoforms in your isoforms.bed file from flair collapse. The bed file output from predictProductivity can be converted to gtf, and then you should see 5UTR/3UTR/CDS fields in the isoforms gtf. 

-Alison

**Comment by abs-yy** [comment]
Hi Alison,

I tried it out, and the errors that I saw earlier looks fine!
However, I'm seeing major decreases in BUSCO completeness (TSS only is 70%, TSS+TES is 50%, reference is 98%). Is this because a lot of these BUSCO genes are not represented in the long read data ?
I'll try predictProductivity as well!
