### ISSUE TITLE
Collapse output nothing in gtf file

### ISSUE THREAD

**Issue by yazuo0204** [BrooksLabUCSC/flair#123]
Hi,

My flair cannot output anything in the gtf file which might influence my downstream analysis.
It looks like this
![image](https://user-images.githubusercontent.com/47863838/87924932-257a8f80-cab2-11ea-9040-62ca2e7b41bf.png)

The version of flair is 1.5.1, and the log presents this:
```
Annotated ends extracted from GTF
Read data extracted
Single-exon genes grouped, collapsing
No GTF conversion was done. Please run bin/identify_gene_isoform.py first
for best results, or run with --force
Renaming isoforms
Aligning reads to first-pass isoform reference
Filtering isoforms by read coverage
```

I'm sure that I have run the identify_gene_isoform.py before I run collapse 
Here is my code 

`python flair.py align -g $ref  -r ../02.Correct/$pre.correct.fa
python bam2Bed12.py -i flair.aligned.bam > flair.aligned.bed12
python identify_gene_isoform.py flair.aligned.bed12 $gtf renamed.bed
pythonflair.py collapse -t 10 -g $ref  -q renamed.bed -f $gtf  -r ../02.Correct/$pre.correct.fa`

**Comment by belgravia** [comment]
So a flair .gtf should be produced as long as you provide a .gtf for the collapse command, which I see that you did. You shouldn't need to run identify_gene_isoform.py before collapse. 
It's weird because the conversion from bed to gtf happens as the last step of flair-collapse but in your log, it printed the "No GTF conversion was done..." message from the psl_to_gtf.py script before it had even determined the final isoform set...
I'm not sure why it's out of order. It could be something about how your terminal is buffering the messages, maybe.

To be safe, I would just advise you to re-run collapse with a .bed file that hasn't been renamed yet (so in this case, flair.aligned.bed12 or flair.aligned.bed) and keep the rest of your collapse command the same. Another thing you can do to be safe is to update your copy of flair, since I think I have made a few commits since I realized v1.5. Finally, you can always generate the gtf if it wasn't generated for reasons relating to the run getting cut off or something by running `python flair/bin/psl_to_gtf.py flair.collapseisoforms.bed > flair.collapse.isoforms.gtf`. I'd suggest doing the last command only if you've inspected your isoforms.bed file and think that the result looks ok.

Other notes about your commands:
- By default, flair align should produce a .bed that you can pass into the other modules. You shouldn't need to run bam2Bed12.py
- Is there a reason why you don't need the correct step?
-Alison

**Comment by yazuo0204** [comment]
> So a flair .gtf should be produced as long as you provide a .gtf for the collapse command, which I see that you did. You shouldn't need to run identify_gene_isoform.py before collapse.
> It's weird because the conversion from bed to gtf happens as the last step of flair-collapse but in your log, it printed the "No GTF conversion was done..." message from the psl_to_gtf.py script before it had even determined the final isoform set...
> I'm not sure why it's out of order. It could be something about how your terminal is buffering the messages, maybe.
> 
> To be safe, I would just advise you to re-run collapse with a .bed file that hasn't been renamed yet (so in this case, flair.aligned.bed12 or flair.aligned.bed) and keep the rest of your collapse command the same. Another thing you can do to be safe is to update your copy of flair, since I think I have made a few commits since I realized v1.5. Finally, you can always generate the gtf if it wasn't generated for reasons relating to the run getting cut off or something by running `python flair/bin/psl_to_gtf.py flair.collapseisoforms.bed > flair.collapse.isoforms.gtf`. I'd suggest doing the last command only if you've inspected your isoforms.bed file and think that the result looks ok.
> 
> Other notes about your commands:
> 
> * By default, flair align should produce a .bed that you can pass into the other modules. You shouldn't need to run bam2Bed12.py
> * Is there a reason why you don't need the correct step?
>   -Alison

Hi Alison

I've found why that things happened, it due to that I use reference from Gencode and gtf file from Refseq. If I convert Refseq gtf name to Gencode, the problem would be solved. 
BTW, the correct step always gives me a empty output. Cause I have already use Illumina reads to correct it, I just skip this step..

Ya
