### ISSUE TITLE
Empty corrected files & No GTF conversion 

### ISSUE THREAD

**Issue by MustafaElshani** [BrooksLabUCSC/flair#128]
Dear Alison 

I am going through FLAIR pipeline, using native RNA sequenced with Nanopore of human cell lines using the biconda env with Gencode references. I am newbie in bioinfomratics any help is appreciated

Align the reads (I think this works FINE)
`flair.py align -r TimeCourse/Control24hr/Control24hr.fastq  -g /TimeCourse/ReferenceGenome/gencode.v34.transcripts.fa -o /TimeCourse/Control24hr/Control24hr.aligned  --nvrna --psl -t 40
`
It outputs 
Control24hr.aligned.psl ,   
Control24hr.aligned.sam , 
Control24hr.aligned.bam, 
Control24hr.aligned.bam.bai,
Control24hr.aligned.bed

Correct Reads (runs but empty files

`flair.py correct -q /TimeCourse/Control24hr/Control24hr.aligned.bed -f /TimeCourse/ReferenceGenome/gencode.v34.annotation.gtf -g /TimeCourse/ReferenceGenome/gencode.v34.transcripts.fa -o /TimeCourse/Control24hr/Control24 --nvrna
`
This outputs 2 empty files
Control24_all_inconsistent.bed
Control24_all_corrected.bed
There is no error given but empty files, why would this be I'm using the correct references?

Collapse (This runs with No GTF conversion

`flair.py collapse  -r /TimeCourse/Control24hr/Control24hr.fastq -q /Control24hr/Control24hr.aligned.psl -f /TimeCourse/ReferenceGenome/gencode.v34.annotation.gtf -g /TimeCourse/ReferenceGenome/gencode.v34.transcripts.fa -o /TimeCourse/Control24hr/Control24 --trust_ends -t 20`

the output files for collapse are
Control24.isoforms.psl 1248KB
Control24.isoforms.gtf 339KB
Control24.isoforms 411KB
The files seem very small, these are generated when the 

```
Filtering isoforms by read coverage
No GTF conversion was done. Please run bin/identify_gene_isoform.py first
for best results, or run with --force
Removing intermediate files/done
```
Why would this be even though I am providing a GTF file 

Any help and advice very much appreciated 

Mustafa

**Comment by belgravia** [comment]
Hi Mustafa,

1) Main thing -- It looks like you are using the transcript sequence fasta file instead of the genome sequence fasta file for `-g` in flair-align and flair-correct. Flair-correct couldn't match the chromosomes in your .gtf to the reference sequence names in the aligned.bed. If this is the case, then please re-run flair from the align step using a genome fasta that has headers which are chromosome names that match the chromosome names in your .gtf file. 

2) For the collapse step, make sure you remember to change `-q` to the corrected reads file, since you had tested it with your aligned reads file. Also, --trust_ends was written with nanopore R2C2 reads in mind, or any reads where you expect little degradation at either the 5' or 3' end of the transcript because of the sequencing method, filtering steps, etc. Just wanted to say that in case you find that you need to reduce the amount of truncated-looking isoforms once you get the collapse step working.

The rest of your commands look ok, thank you for posting them and including all the details of running. Thanks for your patience with my response.

Best,
Alison

**Comment by MustafaElshani** [comment]
Dear Alison

Thank you for your reply very appreciate it. The solution was starring at me all along. As you pointed out providing the genome reference rather then transcriptions worked and I managed to get the corrected reads
Mustafa
