### ISSUE TITLE
Flair collapse and quantify "--stringent" option.

### ISSUE THREAD

**Issue by JasperBoom** [BrooksLabUCSC/flair#165]
Hello devs,

The flair toolsuite is very interesting!
I have been testing it on a in house direct rna nanopore dataset.

I did have a question about the `--stringent` argument in the `collapse` step.
The description of the `--stringent` options says:
`Specify if all supporting reads need to be full-length (80% coverage and spanning 25 bp of the first and last exons)`
As described [here](https://github.com/BrooksLabUCSC/flair/issues/104#issuecomment-600356129), the option actually limits to a filter where at least 3 supporting reads need to be full-length.

Since the message is from march 18 2020, I was wondering if this was still the case? My results would seem to say yes.

If so, I was hoping to have some way to alter flair which would make `--stringent` only use the "full-length" reads.
So disregard the shorted reads for a isoform which is longer.
Currently, if I understand it correctly, the quantification of a dataset which used `--stringent` during collapse would also include
shorter reads in the abundance of a isoform.
Would it be possible to report only the abundance of "full-length" reads?
Any idea if this is possible with a small edit of the code?

A second question, I see that using the `--stringent` option results in far less isoforms than without using `--stringent`.
As expected ofcourse. But I do see a increase in the total abundance when I run quantification.
So the total number of reads per sample is higher with `--stringent`.
Is this because reads that overlap multiple isoforms in the default setting only overlap one isoform (potentially) with the `--stringent` setting and can now be confidently assigned to a isoform?

Thanks you for your help in advance!

**Comment by Jeltje** [comment]
Hi Jasper, 

``--stringent`` only uses reads that cover al splice sites of an isoform (plus at least 25nt of both terminal exons), meaning **shorter reads will not get counted**. The minimum number of reads needed to report an isoform is 3, and you can change that with the ``--support`` setting. 80% is a fairly arbitrary cutoff, because the 'must cover all splices' requirement is what matters.

I am not seeing an increase in total counts when I run with and without stringent, but it is possible that changes to the code have been made between when you posted this question and now (I took over a few months ago). 
Could you try running the latest version? You can install it with conda (see https://flair.readthedocs.io)

I am closing this ticket; please reopen it if you still have this issue.
