### ISSUE TITLE
Fatal error: unable to initialize the JIT

### ISSUE THREAD

**Issue by wenmm** [BrooksLabUCSC/flair#202]
Hello, but when I run flair.py  diffExp and diffSplice, I came across this problem and I'm struggled.
"""
Error in `::`(base, quote) : could not find function "::"
Error in `::`(base, quote) : could not find function "::"
Error in `:::`(compiler, checkCompilerOptions) :
  could not find function ":::"
Fatal error: unable to initialize the JIT
"""

**Comment by Jeltje** [comment]
This issue is probably due to your local R installation, please google the error message to see how to fix it.

It might be easier to run Flair from its docker container:

`docker pull brookslab/flair:latest`

You can then run flair commands like so
``docker run -v `pwd`:/mydata -w /mydata brookslab/flair:latest flair diffExp (...)``

(note that you no longer need the .py extension after flair)

If this solves your problem to your satisfaction, please close this ticket.

We are working to make Flair conda installable but this might take a while.
