### ISSUE TITLE
Unable to run bam2bed12

### ISSUE THREAD

**Issue by gcorre** [BrooksLabUCSC/flair#219]
Hi,
I tried to use the bam2bed12 command but it returns a python module error : 
```
Traceback (most recent call last):
  File ".snakemake/conda/e09a8bd3f2600936d38edd8a28857cb8/bin/bam2Bed12", line 24, in <module>
    from samJuncs import SAM
ModuleNotFoundError: No module named 'samJuncs'
```

The command was  `bam2Bed12 -i  xxx.bam > xxx.bed` using the FLAIR version 1.6.3, installed using conda yaml file in `misc/flair_basic_conda_env.yaml`

Reads were mapped using minimap2 (2.24) and sam files manipulated using samtools v1.9

thanks for your help,
Best

**Comment by Jeltje** [comment]
Thanks for reporting this problem.

We're working on a better solution but you should be able to run `bam2Bed12.py` from the python PATH instead. The link should look something like this:
.snakemake/conda/e09a8bd3f2600936d38edd8a28857cb8/lib/python3.10/site-packages/flair/bam2Bed12.py

Let me know if that works?
Please leave this ticket open, we will close it when the bug is fixed.

**Comment by gcorre** [comment]
Hi,
thanks for the solution, it worked from the python script.

best,

**Comment by Jeltje** [comment]
Fixed, will be present in next release (current release: 1.6.3)
