### ISSUE TITLE
"Superset isoform" definition in flair filter_collapsed_isoforms.py

### ISSUE THREAD

**Issue by mariachiaragrieco** [BrooksLabUCSC/flair#244]
Hi, 

I'm re-doing some analysis using the newest FLAIR version that I have done before using version 1.5, noticing that the number of reconstructed isoforms decreases. 

In this light, I have a question regarding the definition of "superset isoform", used in the flair collapse step (specifically, in the filter_collapsed_isoforms.py subprogram ).

As explained here #210 , I understood that:
- before the release 1.6.2: "An isoform that is a subset of another isoform was filtered out unless the shorter isoform is more abundant that the average expression of the superset isoforms, in which case it is kept"
- after the release 1.6.2: "short isoforms are now only kept if they are more abundant than the most expressed superset"

What I have not clear yet regards what is meant by 'superset isoform'. 
Could you enlighten me? 

Thank you very much.

Kindly, 

Mariachiara

**Comment by Jeltje** [comment]
The superset isoform is the longest isoform of a set. 
Say numbers represent exons, then
2-3-4-5
3-4
3-4-5
are all part of the same set. The superset isoform here is 2-3-4-5.
2-3-5 is not part of that set, because it cannot be merged with the isoforms above.

If that's clear, please close this ticket. If not, leave a comment. Thanks!

**Comment by mariachiaragrieco** [comment]
Hi @Jeltje , thanks for your kind reply.
I understood now what the superset isoform represents. I have two questions regarding how the filter is carried out.
Let's say we have a set composed of isoforms having exons:
**A**) 2-3-4-5
**B**) 3-4
**C**) 3-4-5

**A** will be the superset isoform.

So, I was wondering:
1) Can the superset be composed of more than one isoform? 

2) In computing the average (old FLAIR release) or the maximum value (new FLAIR release) for the filtering threshold, will be considered only the isoforms matching the A structure?

Thanks in advance for you availability.

Kindly,

Mariachiara

**Comment by cafelton** [comment]
You can have multiple supersets for one gene, for instance, if all junction chains expressed are:
2-3-4-5
3-4
3-4-5
1-2-3-5
2-3-5

There are 2 non-overlapping supersets: 2-3-4-5 and 1-2-3-5, as neither of these is a subset of the other
2-3-4-5 contains 3-4 and 3-4-5
1-2-3-5 contains 2-3-5

If we bring in expression:

50 reads: 2-3-4-5
20 reads: 3-4
10 reads: 3-4-5
15 reads: 1-2-3-5
20 reads: 2-3-5

The final isoforms would be 2-3-4-5, 1-2-3-5, and 2-3-5

Neither subset of 2-3-4-5 has higher expression than it, so it would be thrown out.
However, the other superset of intron junctions is considered separately, and since 2-3-5 has greater expression than 1-2-3-5, it would be kept
