### ISSUE TITLE
Question regarding number of reads.

### ISSUE THREAD

**Issue by eprdz** [BrooksLabUCSC/flair#256]
I have a question regarding the reads that are used in the collapsing step.
If I use the "generate_map" option, the number of reads that I get from the *_combined.isoform.read.map.txt should be the same as the number of reads that are in the *_all.corrected.bed that is the output of flair correct?

Surprisingly, sometimes I get more reads in the *_combined.isoform.read.map.txt file than in the *_all.corrected.bed file.

**Comment by cafelton** [comment]
If you are using --annotation_reliant, it also aligns to the transcriptome. This can allow additional reads to be used as transcript support than align well to the genome.
You can also get less reads than in _all_corrected.bed, since collapse does not have to assign every read to a transcript - it may decide a read is truncated or has too many errors around splice sites and not assign it
