### ISSUE TITLE
Basic questions to FLAIR for use with 1D cDNA reads

### ISSUE THREAD

**Issue by drc111** [BrooksLabUCSC/flair#28]
I am quite new in bioinformatics and currently implementing FLAIR in our lab. Thus, I have some basic questions I hope will answer:

1) For 1D cDNA reads, would you recommend using the -n flag in during FLAIR align?

2) In Tang et al. 2018, you mention that you used mRNAtoGene following spliced alignment mapping with minimap2. Is mRNAtoGene integrated in the FLAIR align module?

3) Though not required, would you recommend including TSS/TES to increase the confidence in the isoforms? Or what is the purpose of this?

Thanks a lot in advance!

**Comment by belgravia** [comment]
Thanks for reaching out and your patience! Happy to help.

1. `-n` flag is probably not necessary for 1D cDNA reads. So the -n nanopore native RNA flag in flair align uses the [minimap2](https://github.com/lh3/minimap2#map-long-mrnacdna-reads) recommended parameters for direct RNA. That looks like `minimap2 -ax splice -uf -k14`. Without specifying the flag, the spliced alignment is done with minimap2 defaults like so: `minimap2 -ax splice`, which according to the minimap2 readme is the recommended command for nanopore 2D cDNA-seq. There's nothing written explicitly for 1D cDNA-seq, so we have been using the 2D cDNA-seq parameters. (Side note: for both direct RNA and 1D cDNA, an additional `--secondary=no` argument is added to the minimap2 call to keep only the primary alignment for each read). 

2. We have since updated how we correct reads. We no longer require mRNAtoGene, as mRNAtoGene functionality has been incorporated into flair-correct.

3. By including the TSS/TES, do you mean the `-i` argument for flair-collapse? 

-Alison

**Comment by drc111** [comment]
Thanks for your comprehensive answers.

In 3), yes, I am referring to the -i argument for flair-collapse.

**Comment by belgravia** [comment]
1) `--secondary=no` is already included in the command from the flair.py wrapper script.

3) If you specify `-i`, then after reads are grouped by their spice junction chains, the most frequently used transcription start and end sites for that isoform group are picked. If `-i` is not specified, then the most frequently used TSS/TESs for all the isoforms of that gene will be used for each isoform. I uploaded a little diagram onto my google drive here to illustrate the difference: https://drive.google.com/open?id=1Aom1_SyhEQYyxjl1n_j86RmEbIFuxRfk

I would specify `-i` if you are interested in transcript start and end sites on an isoform-level. In terms of isoform sensitivity, you will still pick up essentially the same number of isoforms regardless of whether you specify or not.

-Alison

**Comment by drc111** [comment]
Thank you!
- Sebastian
