### ISSUE TITLE
Question on corrected reads 

### ISSUE THREAD

**Issue by ljw90607** [BrooksLabUCSC/flair#34]
Hi!

I had some question on the wonderful script that you have provided.

1. For the flair-correct, what criteria does this algorithm uses to differentiate reads with corrected and inconsistent? Would there be any option to modify the filtering parameter?
2. For the flair-collapse step, does it only use the reads that are corrected, not the inconsistent reads? If so, I am losing quite a lot of the reads to inconsistent reads from flair-correct step. (about a half) and is this alright?

Thank you for your wonderful help!

**Comment by belgravia** [comment]
1. In flair-correct, reads are assumed to be correct if they contain splice sites found in the user-provided annotations/junctions files. Moreover, the splice sites for each read can be a certain distance from annotated splice sites and still be considered correct. The max distance from annotated splice sites is a user-set parameter. If a single splice site is not consistent with the user-provided annotations/junctions file, then the read is considered "inconsistent."

2. It is recommended to only supply FLAIR-collapse with the corrected reads. Supplying both the corrected and the inconsistent reads to the collapse step would potentially result in more erroneous isoforms in the final set. If the corrected reads file only contains half of your reads, this should be fine (unless you are looking to maximize isoform discovery). The corrected/filtered reads are the better reads for flair-collapse to use to build first-pass isoform models. All reads (`-r`), including the rest of your reads that weren’t able to be corrected, are still involved in the collapse step since they are used to quantify the first-pass isoforms. 

-Cameron and Alison

**Comment by ljw90607** [comment]
Thank you very much for the reply and sorry for the late response.

I have noticed that all of my data that I have ran through the Flair correct, half (or even more) of the reads are filtered as inconsistent. But when I look at their transcript structure on the IGV, they don't seem to have much issue, therefore I feel like I am losing quite a lot of reads from that step.
I have also tried the window option upto 100 and did not help much.
Should I still remove the reads that are filtered as inconsistent? or would there be any way that I can use these information for the further analysis?

Thank you very much for your generous help again!

Jungwoo

**Comment by belgravia** [comment]
Hi Jungwoo,

Can you share an example of a read in the inconsistent file that you think should be corrected? That would be helpful for us to see if it's an issue with the correction script.

The inconsistent reads will still be used in FLAIR-collapse even if they're filtered out in the correction step. The corrected reads are used to define a firstpass set of isoforms, which is then reduced into a smaller set using the inconsistent and corrected read sequences as increased evidence for the firstpass set of isoforms. Assuming you still have multi-exonic reads in your corrected reads file, I would not be too concerned. It may be worth running flair-collapse and looking at the final isoforms by eye. Let me know how that goes.

-Alison

**Comment by ljw90607** [comment]
Dear @belgravia 

Thank you very much for your helpful comment and I will try the correction step.
I will leave the example file here for you to check on them. (1 corrected, and 1 inconsistent bed files)
(https://www.dropbox.com/s/en077te5fy58wff/sample_example.zip?dl=0)

If you could tell me anything about the data, It will be very helpful to me!
Thank you again for your help!


Jungwoo

**Comment by shamsbhuiyan** [comment]
> 1. In flair-correct, reads are assumed to be correct if they contain splice sites found in the user-provided annotations/junctions files. Moreover, the splice sites for each read can be a certain distance from annotated splice sites and still be considered correct. The max distance from annotated splice sites is a user-set parameter. If a single splice site is not consistent with the user-provided annotations/junctions file, then the read is considered "inconsistent."
> 2. It is recommended to only supply FLAIR-collapse with the corrected reads. Supplying both the corrected and the inconsistent reads to the collapse step would potentially result in more erroneous isoforms in the final set. If the corrected reads file only contains half of your reads, this should be fine (unless you are looking to maximize isoform discovery). The corrected/filtered reads are the better reads for flair-collapse to use to build first-pass isoform models. All reads (`-r`), including the rest of your reads that weren’t able to be corrected, are still involved in the collapse step since they are used to quantify the first-pass isoforms.
> 
> -Cameron and Alison

Follow up question to JungWoo's original question. If I provide splice junction data from short reads that were mapped to Ensembl gtf annotations, and Ensembl annotations to the flair correct step, is this redundant? Furthermore, if I remove any junctions that had no mapped short reads, but then I still provide the Ensembl gtf annotations, will FLAIR correct on all splice junctions anyways?

**Comment by csoulette** [comment]
Hi shamsbhuiyan,

> If I provide splice junction data from short reads that were mapped to Ensembl gtf annotations, and Ensembl annotations to the flair correct step, is this redundant?

If you've aligned your short-read data using parameters that only allow alignments that correspond to the user-defined GTF, then using short-read junctions and annotations would be redundant.

If you've aligned your data using annotations, but without transcriptome-only alignments, then using short-read junctions and annotations would not be redundant.

The deeper question your comments touch on are  "what is the overlap of junctions found in a short-read experiment versus some highly-curated gtf annotation, like ensemble." The short/generalized answer is that there is "a lot" of overlap between short-read junctions and annotations, but the overlap highly depends on the annotations that you are using and the biological conditions of the sample you've sequenced. 

>  ... if I remove any junctions that had no mapped short reads, but then I still provide the Ensembl gtf annotations, will FLAIR correct on all splice junctions anyways?

Yes. In short, the junctions you input are the junctions used to correct against. Expression levels of the junctions are not considered. Something that we typically do before correction is filter our junctions based on some criteria ( number of uniquely mapped reads and splice site motif ).

-CMS

**Comment by shamsbhuiyan** [comment]
Hi CMS, 

Thanks for your response. So I tried to run FLAIR correct without a GTF annotation and with just splice junction annotations generated from STAR: 
```
python ~/flair/flair.py correct -q flair.aligned.bed -c ~/rn6.ch
rom.sizes -j ../../SJ.out.tab -g /space/grp/Pipelines/rnaseq-pipeline/Assemblies/Rattus_norvegicus/Ensembl/Rnor_6.0/Sequence/WholeGenomeFasta/genome.fa -t 20
```
But when I run the command, I get this error and the program terminates:
```
Step 2/5: Processing additional junction file  ../../SJ.out.tab ...Traceback (most recent call last):
  File "/home/sbhuiyan/flair/bin/ssCorrect.py", line 410, in <module>
    main()
  File "/home/sbhuiyan/flair/bin/ssCorrect.py", line 328, in main
    if otherJuncs != None: juncs, chromosomes = addOtherJuncs(juncs, otherJuncs, chromosomes, genomeFasta, knownSS)
  File "/home/sbhuiyan/flair/bin/ssCorrect.py", line 145, in addOtherJuncs
    if key in juncs[chrom]:
KeyError: '10'
Correction command did not exit with success status
```

**Comment by csoulette** [comment]
Hi shamsbhuiyan,

Thanks for pointing this out for us. I just updated ssCorrect.py ( 29e8013 ), and you should now be able to move forward with short-read only junction correction. Let me know if this issue persists. Thanks!

-CMS

**Comment by shamsbhuiyan** [comment]
Thanks. The new version seems to be working

**Comment by csoulette** [comment]
Hi @ljw90607 ,

I'm taking a look at your data and need a bit more information to try to narrow down whats going on here. Could you include your usage syntax? Additionally, it would be very helpful if you could forward the temporary junction bed files created during correction. You can obtain these by calling on ssCorrect.py directly with the following syntax:

`python3 ~/bin/flair/bin/ssCorrect.py -i flair.aligned.bed -g annotation.gtf -o test -f genome.fa -p N --keepTemp`

The splices sites that are consistent with annotations/short-read data are defined in the intermediate junction files, and so taking a look at them will be insightful. 

Thanks ~
-CMS

**Comment by ljw90607** [comment]
Dear @csoulette,

Thank you for the reply! Here is the syntax I used below and also attaching the link which contains the intermediate junction files that you have asked. Previously I have not used the short-read data to refer the splice site.
`python3.5 flair.py correct -c /reference/hg38.chrom.si
zes -g /reference/hg38.fa -q $flair.align.bed -f /reference/Homo_sapiens.GRCh38.93.gtf`

https://www.dropbox.com/s/34ftz4l2c2h8k52/tmp_1ebafd0c-4413-45ca-b887-75eefd83a124.zip?dl=0

Thank you very much for your help!
Jungwoo

**Comment by csoulette** [comment]
Hi Jungwoo,

Thanks for providing all of this information. I found the issue which had to do with a very small formatting style that Ensemble uses for their GTFs. Thanks for your patience! Please pull the latest changes to ssCorrect.py ( a7d2927 ). The amount of reads that get filtered varies, and really depends on the dataset and annotation set. I've taken look at your data and checked a few loci with inconsistent read pileups. From the few loci i've looked at, the reads seem to contain at least 1 splice site more than 10 nucleotides from any splice site contained in the annotations. The correction seems to be working, but please let me know how the run goes after updating.

Thanks~

-CMS

**Comment by ljw90607** [comment]
Dear @csoulette 

Thank you very much for your wonderful help. 
I have just checked the data with the new ssCorrect.py and it did decrease a lot of reads that were annotated as inconsistent reads previously.

Just trying to understand how this issue was fixed, I cannot fully understand what exactly is fixed from the annotation file.
Could you please explain what you meant by the small formatting style of Ensemble?

Thank you again for your wonderful help!

Jungwoo

**Comment by csoulette** [comment]
Hi Jungwoo,

The issue wasn't very exciting, which is why I didn't detail the remedy, but i'd be more than happy to elaborate! 

During the first step of correct, the user input GTF annotation file is processed to extract spliced junction coordinates. These junction are used to define splice sites that are "consistent" with the annotations. The way junction are extracted is by first collecting all exon coordinates for each transcript, sorting them by position, and extracting the coordinate positions that correspond to intronic regions. In order to do this, the exons need to be linked to a common ID (the transcript ID).  Usually GTF annotation files will have a transcript ID for each exon entry, and the the format describing transcript ID is fairly similar across GTF files from different sources (i.e. gencode vs ensembl). However, sometimes there are subtle differences between GTF files, like delimiters or the column position containing the transcript ID information. 

That being said, the issue of over-filtering reads was due to that fact that intron junction coordinates were not being correctly computed, and this was due to incorrectly linking exon coordinate information using the wrong transcript ID field in the GTF file. Moreover, because junctions were being incorrectly computed, splice sites that should have been considered consistent were not.

Hopefully this helps!

Best,
CMS

**Comment by ljw90607** [comment]
Dear @csoulette 

Thank you very much for your wonderful help!!
