### ISSUE TITLE
How does flair quantification work?

### ISSUE THREAD

**Issue by dudududu12138** [BrooksLabUCSC/flair#343]
**I have read the paper (https://doi.org/10.1038/s41467-020-15171-6)  
and the manual (https://flair.readthedocs.io/en/latest/) and I still have a question about**
- quantify
In your manual,`flair quantify` only needs 2 parameters: 1) `the transcripts(.fasta)` ; 2) `the raw reads(.fastq)`. My questions are:
1. How did you assign the reads to transcripts? What alignment tool does flair quantify use? Is it still minimap2 in the `flair align` step? If so ,why not use the bam file directly? 
2. The mapping quality of the raw reads are different. If `flair quantify` use raw reads directly while the bam files in the align step are filtered with mapping quality, then the reads are not matched between quantify step and identification step.

Thank you！Looking forward to your reply!

**Comment by cafelton** [comment]
It realigns the reads to the transcripts using minimap2. It allows secondary alignments and then compares all alignments to similar transcripts to identify the one with the best match. You can't input the bam file because it's a completely different alignment. 
The reads from the quantify step are not meant to be matched to the collapse/identification step. If you want the exact reads from the identification step, you can parse combined.read.map.txt from collapse. The idea is that you can use different parameters for collapse and quantify - so be stringent for transcript identification, then more permissive for quantification to recover more reads
