### ISSUE TITLE
Identified isoforms can be found in UCSC genome browser

### ISSUE THREAD

**Issue by leafiezyt** [BrooksLabUCSC/flair#38]
Hi,

I can successfully run through flair pipeline and obtain quite a lot novel isoforms. But when I import randomly a few into UCSC genome browser and it seems to me that the isoforms are already identified, which is not novel. 

I am currently using gencode version 31, which is the latest. I used Comprehensive gene annotation GTF file for PRI assembly (https://www.gencodegenes.org/human/). 

I also attached a screenshot here for one of the isoforms.  Am I missing something here? My primary purpose is to identify novel isoforms. My track is the top one and you can see that we can find exactly the same one among one of the tracks below.

Thanks a lot for developing such a handy tool for the nanopore RNAseq community.

Best,
Yeting

![test](https://user-images.githubusercontent.com/10110787/61155349-b8a3e100-a4be-11e9-9c6a-0125d3e6f141.PNG)

**Comment by belgravia** [comment]
Hi Yeting,

Just to clarify -- the top track contains 1 isoform that FLAIR found, and FLAIR told you it was novel (didn't assign it to the annotated isoform ENST... name)? I assume you ran FLAIR collapse with the `-f` option to give it your gencode gtf. 

If that's the case, I would want to take a look at this particular isoform's PSL entry if that's ok with you.

-Alison

**Comment by anbrooks** [comment]
Yeting, I think your custom track needs to be expanded to "full" to see all the isoforms. It is likely in dense mode since the introns do not have the small arrows.

**Comment by leafiezyt** [comment]
Thanks a lot for the comments. I attached another screenshot here. The PSL entry is listed below. Another strange thing with my output files is that flair.collapse.isoforms.gtf is empty for my run. I ran an additional step of using identify_gene_isoform.py to annotate the reads id in the PSL file. 

2465	0	0	0	0	0	0	0	-	7267dea5-353b-4c4c-9829-72b0d9494e35_chr1:1233000	2465	0	2465	chr1	248956422	1233547	1235064	1	1517,	0,	1233547,
![test2](https://user-images.githubusercontent.com/10110787/61160344-1b9c7480-a4cd-11e9-988f-40aff0e3bd47.PNG)

**Comment by belgravia** [comment]
So I took a look at that PSL entry you sent in the genome browser. I was looking at gencode v29 comprehensive since it didn't have v31, but I think it should be ok.

FLAIR is a little strict with assigning single exon transcripts to known transcripts. It requires that the FLAIR transcript cover at least 80% of the annotated isoform, and in this case annotated B3GALT6 is much longer. The 80% number was not a user-tunable parameter, but I have fixed that in the most recent commit. Try running identify_gene_isoform.py again with syntax something like `python identify_gene_isoform.py annotation.gtf yourisos.psl yourisos_renamed.psl 0.5` and let me know how that goes. 

1. Would you still be able to send me that other isoform that you said looks like it should be an annotated isoform but was called novel? 
2. FLAIR-collapse should run identify_gene_isoform.py for you if you provide an annotation. Strange that FLAIR collapse didn't generate the GTF properly. You can try making it with bin/psl_to_gtf.py and let me know how that goes.

![Screen Shot 2019-07-12 at 4 19 36 PM](https://user-images.githubusercontent.com/5727343/61163102-f570d780-a4c0-11e9-9178-80e1e835a4e8.png)

-Alison

**Comment by leafiezyt** [comment]
Hi Alison,

Thanks so much for your help. I will follow your suggestions and rerun the code with 50% coverage as a cutoff and let you know the update.

As for the other isoform, I checked again and that one is annotated with a certain ENGXXXX name, so it's not a novel isoform. Please accept my apology for not clarifying that in the previous post.

Again greatly appreciate your help here.

Best,
Yeting

**Comment by leafiezyt** [comment]
Hi Alison,

This is Yeting. Thanks for your help in the past. I have another question here. I noticed that a lot of my novel isoforms identified are actually partial 5'UTR or 3'UTR regions. I attached one example below here.

4229 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | - | edb6d3bc-3e86-4ade-bb66-1bbedeb344c7_chr15:67190000 | 4229 | 0 | 4229 | chr15 | 101991189 | 67190965 | 67195194 | 1 | 4229, | 0, | 67190965,

![UTR_novelisoform](https://user-images.githubusercontent.com/10110787/61296697-a076df00-a7a8-11e9-90fc-4fdc8892dab5.PNG)

I wonder if this kind of novel isoforms identified by Flair is due to degraded transcripts? I am trying to think about the next steps at this point. Any suggestions/insights are welcome.

Thanks,
Yeting

**Comment by belgravia** [comment]
Those are potentially from degraded transcripts. FLAIR tries to build the most complete isoforms it can. E.g. if the partial isoforms are subsets of longer isoforms, then the partial isoforms are removed. In this case, since FLAIR did not assemble any spliced isoforms for SMAD3, this partial 3' UTR isoform is kept. You can avoid assembling short 3' UTR isoforms if you specify in the collapse step a bed file of genomic regions where start sites are acceptable. In the Workman et al bioRXiv using native RNA sequencing, we used inferred promoter regions.

Assuming that there isn't read support for longer isoforms that you think FLAIR may be missing, I would probably not think about these particular cases too much in downstream analyses and turn to more highly expressed genes.
-Alison

**Comment by leafiezyt** [comment]
Alison,

Is there a way to directly tell that a specific novel isoforms is residing entirely in the 5'UTR or 3'UTR regions based on the PSL output? I can only think of writing a code to compare the GTF annotation to the coordinates to the PSL output. Let me know if there're other ways or Flair might have such fucntion that I am not aware of. 

I want to filter out these kind of novel isoforms to rule out false positives here.

Thanks,
Yeting

**Comment by belgravia** [comment]
Currently there isn't any code in FLAIR to do this. You could either write your own, or try filtering out the isoforms that don't match annotated genes (i.e. the ones where the gene is `chr...`).
-Alison
