### ISSUE TITLE
FLAIR collapse misidentifying (and missing) isoforms

### ISSUE THREAD

**Issue by DepledgeLab** [BrooksLabUCSC/flair#44]
I'm having lots of fun using FLAIR to look at transcript isoforms, particularly in situations with lots of overlapping (polycistronic) transcripts, but am noticing some unusual outputs that don't make sense from looking at the read data. The attached screenshot showcases several of these curiosities.

![Untitled-1](https://user-images.githubusercontent.com/32496778/63184394-3e1e3200-c025-11e9-8d87-0c048c8910bf.jpg)

Issue #1: Transcript isoforms shown in the wrong orientation. The left most transcription unit (gene A) comprises two exons on the forward strand. FLAIR correctly identified this but for some reason also shows some transcript isoforms as being present on the reverse strand. This is not obviously supported by the read data and I am curious as to why this is happening?

Issue #2: Distinct transcripts are being merged together. Next to the two exon transcript (on the forward strand) is a single exon transcript (gene B). For some reason FLAIR is merged this transcript with the previous one to create an alternative isoform. While this isoform is supported by a small subset of read (and is due to read-through transcription), the vast majority of reads support gene A and gene B as distinct entities. I am not clear why FLAIR isn't therefore presenting an isoform for gene B alone?

Issue #3: The next transcription unit (gene C) is on the reverse strand but no isoform is detected by FLAIR, regardless of whether using the --stringent setting or not.

Issue #4: The right most transcript unit suggests the presence of a two exon transcript. This is supported by a subset of reads but like Issue #2, additional transcript isoforms are not shown.

I should note that the transcripts I am describing (expecting) are all experimentally validated with confirmed TSS and TES data. I figure that if I can optimize the parameters for FLAIR so that I can generate an output close to 'reality' then I can apply this to the remainder of the genome in which transcripts are less well defined.

I am continually experimenting with different parameters (-w, -s, --max_ends) to try and resolve this but no joy yet. What I do have though is data on TSS and TES derived both from other techniques (e.g. CAGE) and from the direct RNASeq data itself. It would be very useful if I could feed this data to FLAIR to inform its decision making around overlapping transcripts.

**Comment by belgravia** [comment]
Hi, thanks for taking the time for writing up a detailed report!! Thanks so much for your patience.

1: It is possible that the wrong strand is being introduced at the correction step. This could happen if that junction is duplicated within/between the splice junction references and is on different strands. Have you taken a look at the corrected reads?

2: I am going to assume that Gene B is Gene 2 in the image you provided. Any Gene 2 isoforms will be filtered out by default if the longer Gene A isoform is present. You can change the filtering behavior with `-e`. I would recommend adding `-e comprehensive --quality 0` to the collapse command. 

3: From just this image, I can't figure out the reason why Gene C/gene 3 is missing. You could run FLAIR with `--keep_intermediate` and inspect the firstpass isoform file to see if Gene C is captured there. That would be helpful for me to debug. You can also specify a directory for the temporary files that are kept with`--temp_dir` that will have other files that are potentially informative. The `--stringent` setting will not help much here, since it controls how reads are assigned to the firstpass isoforms to determine how many supporting reads there are for each firstpass isoform.

4: FLAIR creates isoform groups of corrected reads that contain the same splice junction chains, and then reassigns all reads to these firstpass isoforms to determine how many supporting reads there are for a given isoform. From the image, it looks like the rightmost isoform won't have enough reads (by default `-s` is 3) supporting the same isoform.

For simplicity and better quantification it is better to keep `--max_ends` a smaller number (by default it is 2). If you are fine with 1 TSS/TES per unique splice junction chain, you can add `-n best_only` to your collapse command. The `-w` parameter toggles how far apart TSS must be from each other to be considered a separate TSS (same with at the TES) and changing w may not be too helpful for these cases. Lastly, if your CAGE TSS data is in .bed format, you can supply it to the collapse command with `-p` to filter for only the reads that have start sites that are within the CAGE-defined TSS regions to define isoforms.

You could try rerunning the collapse command with the parameters I have recommended. Let me know how it goes.

-Alison
