### ISSUE TITLE
Error with collapse

### ISSUE THREAD

**Issue by zwardnz** [BrooksLabUCSC/flair#45]
I was running flair.py collapse:
`flair.py collapse -f genome.gtf -g genome.fa -r sample.fastq -q corrected.psl`
and got the following error:

> Annotated ends extracted from GTF
> Read data extracted
> Single-exon genes grouped, collapsing
> Filtering isoforms
> Renaming isoforms
> Traceback (most recent call last):
>   File "/home/zoe/bin/flair-master/bin/identify_gene_isoform.py", line 177, in <module>
>     if tn_to_juncs[chrom][t] == junctions:
> KeyError: '3'

Please help?

**Comment by belgravia** [comment]
Hi,

Can you check to see if the chromosome names in your gtf and in your fa are formatted the same? E.g. `chr3` in one and `3` in another. It might be helpful to see a couple lines from each file.

-Alison

**Comment by zwardnz** [comment]
They look to be the same. However I am using an artificial chromosome (chrIS) as I'm using synthetic spike in RNA - 'Sequins' [https://www.sequinstandards.com/](url)
I have concatenated this onto the GRCh38 fatsa and also the gencode gtf (and the naming is the same):
`tail gencode.v31_chrIS.gtf`

> chrIS   Sequin  exon    10389977        10390029        .       +       .       gene_id "R2_59"; transcript_id "R2_59_3";
> chrIS   Sequin  exon    10390348        10390403        .       +       .       gene_id "R2_59"; transcript_id "R2_59_3";
> chrIS   Sequin  exon    10394053        10394235        .       +       .       gene_id "R2_59"; transcript_id "R2_59_3";

`cat GRCh38.r97_sequin.fa | grep '>chrIS'`

> >chrIS

I've also just tried to run flair.py align and encountered another problem:
`$ python /home/zoe/bin/flair-master/flair.py align -t 20 -o flair -g /media/chi/zoe/STAR_GRCh38/GRCh38.r97_sequin.fa -r ../../fastq_pass/cleveland_heart.fastq -p -v1.3`
```
[M::mm_idx_gen::86.102*1.78] collected minimizers
[M::mm_idx_gen::92.838*2.92] sorted minimizers
[M::main::92.838*2.92] loaded/built the index for 195 target sequence(s)
[M::mm_mapopt_update::96.640*2.84] mid_occ = 762
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 195
[M::mm_idx_stat::98.798*2.80] distinct minimizers: 168242330 (35.56% are singletons); average occurrences: 6.015; average spacing: 3.074
[M::worker_pipeline::288.789*13.82] mapped 970196 sequences
[M::worker_pipeline::472.315*16.21] mapped 981059 sequences
[M::worker_pipeline::661.845*17.29] mapped 923072 sequences
[M::worker_pipeline::867.740*17.89] mapped 804540 sequences
[M::worker_pipeline::1064.256*18.27] mapped 866221 sequences
[M::worker_pipeline::1255.979*18.53] mapped 898746 sequences
[M::worker_pipeline::1440.601*18.71] mapped 937388 sequences
[M::worker_pipeline::1545.092*18.77] mapped 547472 sequences
[M::main] Version: 2.11-r819-dirty
[M::main] CMD: minimap2 -ax splice -t 20 --secondary=no /media/chi/zoe/STAR_GRCh38/GRCh38.r97_sequin.fa ../../fastq_pass/cleveland_heart.fastq
[M::main] Real time: 1545.422 sec; CPU: 29001.106 sec
Converting sam output to bed
[E::sam_parse1] CIGAR and query sequence are of different length
[W::sam_read1] Parse error at line 2783503
[main_samview] truncated file.
Possible issue with samtools executable
```

Do you have any suggestions? This is a cDNA ONT experiment. Does flair.py align have an option similar to '-ax splice'???

**Comment by zwardnz** [comment]
I ask because I have what looks like a two exon transcript (please see attached). All of the spliced reads support a two exon transcript but the flair annotation (the top annotation is the output of flair correct, the second one is the output of flair collapse (I can only get it to work up to the first pass isoform set)) is assigning many exons without support of spliced reads. Is this what you expect? If I can get it running to the high confidence isoform set would this help with this??

[ONT2.docx](https://github.com/BrooksLabUCSC/flair/files/3528030/ONT2.docx)

**Comment by zwardnz** [comment]
I also have something like this transcript that flair seems to be missing completely???
[ONT3.docx](https://github.com/BrooksLabUCSC/flair/files/3528099/ONT3.docx)

**Comment by belgravia** [comment]
Ok, if FLAIR is only identifying single-exon reads, that typically means that there was an issue with FLAIR-correct. If you double check the corrected reads psl, it should be that starting from there, there won't be the multi-exonic reads that you expect.

If FLAIR is missing only the _unannotated_ multi-exonic transcripts, then that is expected behavior. This is assuming you do not have splice junctions determined from short-read sequencing. FLAIR puts any reads that have unsupported splice junctions in the inconsistent.bed file, so these reads will not be used for isoform detection in the collapse step (they are included in `-r` since they are used to help quantify the isoforms that have fully-supported splice junctions). If you want, you could try concatenating the inconsistent.bed reads as a psl and giving that to FLAIR-collapse. You may end up with undesired isoforms, however. 

Also, I'm not exactly sure why running FLAIR-correct with sequins and your other cDNA would cause an issue with collapse. If you can, could you point me to where I can download the sequins GTF? I'd just like to see more entries. We've previously had issues with parsing different GTFs from different sources...

Less relevant, but when running gffcompare I like to add `-R` so that annotated transcripts that are not present in your sample aren't included.

-Alison

**Comment by zwardnz** [comment]
Thanks for your reply Alison. I will give that a go.
If you register at www.sequinstandards.com/login you can download that sequins GTF from there.

Also thanks for the tip regarding gffcompare.
