### ISSUE TITLE
flair collapse -s not passed to collapse_isoforms_precise.py

### ISSUE THREAD

**Issue by mjblow** [BrooksLabUCSC/flair#57]
I'm running flair using docker (v1.4). The value specified using -s in flair collapse, does not seem to be passed to collapse_isoforms_precise.py, and this always runs with -s 1. Maybe a minor bug in flair.py:

In flair.py, lines 235-6:

	collapse_cmd = [sys.executable, path+'bin/collapse_isoforms_precise.py', '-q', precollapse, \
			'-m', str(args.max_ends), '-w', args.w, '-s', '1', '-n', args.n, '-o', args.o+'.firstpass.unfiltered.psl']

**Comment by belgravia** [comment]
That is actually intentional. I apologize for the confusing use of `-s` in the wrapper and `-s` for one of the scripts called internally. 

The collapse_isoforms_precise.py script generates the firstpass isoforms, which don't have a minimum supporting read threshold (in some cases, 1 read is sufficient to define an isoform). However, the `-s` specified in flair collapse is used to filter out the first pass isoforms that don't have enough coverage from the re-assignment step.

That being said, I am in the process of changing the way the firstpass isoforms are generated such that for a given splice junction chain, after the best TSS and TES are called, the following TSS/TES must comprise s% of all the reads.
