### ISSUE TITLE
invalid strand in PSL

### ISSUE THREAD

**Issue by diekhans** [BrooksLabUCSC/flair#60]
Flair correct+ collapse is generating strand in the form "+(+)" which is not valid and breaks downstream processing software.

Were is this generated and what does it mean?

**Comment by csoulette** [comment]
Hi @diekhans ,

Thanks for pointing this out. We found the issue to be caused by a difference in bedtools getfasta. In an older version (2.25), the strand information was stored as a single character string (i.e. "+" or "-"). In a newer version, the strand information format was changed so that the strand is embedded within parentheses ( i.e. "(+)" or "(-)"). ssCorrect assumed the strand info follows the bedtools v2.25 format, not the 2.27. We've now included extra logic in ssCorrect for account for this change, and any future changes in strand formatting by bedtools. You will find that the latest version of ssCorrect should resolve this issue ( 47fd0cbd ). Thanks!

-CMS
