### ISSUE TITLE
error in correct

### ISSUE THREAD

**Issue by cym0304** [BrooksLabUCSC/flair#7]
Hi,
    I noticed that the FLAIR can use the short reads to correct the nanopore reads. And the example shows that I need to use the shortreads.sam as the infile. And my question is how can I get the shortreads.sam file. Is it got by mapping the Illumina reads to the reference with the alignment software?

**Comment by csoulette** [comment]
Hi YunmeiChen,

Yes, you are correct. The shortbreads.sam file can be obtained by mapping the illumination reads to the reference with short-read alignment software such as STAR (https://github.com/alexdobin/STAR) or HISAT. If you choose to use STAR, you can simply use the junctions.out.tab file that STAR provides as part of alignment output output. Let me know if there are anymore questions!

~Thanks

-CS

**Comment by YunmeiChen** [comment]
Hi，
Thank you for your reply. I tested the FLAIR pipeline to get the consensus sequences of Nanopore data. But the number of final consensus is too small to use. 
My data has more than 20 million raw reads but I only got 26221 consensus sequences. I tried to change the parameter -s from 3 to 1, but it didn't work. When I set the -s as 1, I got 51033 consensus reads. What's more, I got more than 2 million consensus reads by racon software with the same data.  
Is it normal? And if I want to get more consensus reads, what should I do?

**Comment by belgravia** [comment]
So setting `-s=1` is exactly what I'd recommend for increasing the number of isoforms from flair-collapse. Otherwise, you'd have to further compromise quality - you could use `*.firstpass.psl`, which is all the isoforms prior to filtering for those that have at least `-s` number of MAPQ>=1 reads assigned to them. You could also change `-e` to `comprehensive`, which won't filter out the partial isoforms unlike the default. 

I suppose it depends what you want to use your isoforms for, and if isoform quality is important, then it may well be that 26,221 or 51,033 are the best numbers you will get from FLAIR.

I'm not entirely familiar with using racon in this context and I'll have to look into more about racon's algorithm to give you a better answer on why racon gives 2 million consensi.

-Alison

**Comment by cym0304** [comment]
Hello,
I tried to set the -s=1. And the number of consensus is  51033. It works, but its's not enough. We want to detect as many transcripts as possible. That means if one transcript is producted in cell, we want to get it in our result. We don't want to lose too much information. But we think the 51033 is smaller than the actual value.
I will try to change -e. I hope it works.
Thanks for your reply. If you have any suggestions, please let me know. 
Best,
Cym

**Comment by callumparr** [comment]
> Hello,
> I tried to set the -s=1. And the number of consensus is 51033. It works, but its's not enough. We want to detect as many transcripts as possible. That means if one transcript is producted in cell, we want to get it in our result. We don't want to lose too much information. But we think the 51033 is smaller than the actual value.
> I will try to change -e. I hope it works.
> Thanks for your reply. If you have any suggestions, please let me know.
> Best,
> Cym

Is is this the write tool for you? The idea is to get consensus isoforms providing a threshold number of reads to be met. If you want to as many isoforms as possible, why not just take the raw mapped reads as your isoforms, than condensing down into consensus isoforms?
