### ISSUE TITLE
some questions on output gtf from FLAIR collapse

### ISSUE THREAD

**Issue by yejilee-biostat** [BrooksLabUCSC/flair#74]
Hello,

 Thank you for your help last time - I have some questions about FLAIR-collapse this time.

 Since data from short read sequencing is available in my case, I have tried the correct module of FLAIR with reference data then run the collapse module like this:

python $flair_loc/flair.py collapse -r input.fastq -q flair.correct_with_reference_all_corrected.psl -g reference.fa -t $num_threads -f reference.gtf -o flair.collapse.correct_w_ref

 The output files are flair.collapse.correct_w_short.isoforms.gtf, fa and psl files. However, when I looked the gtf file, I have found the following issues:

(1) gene names in the gtf file don't match with the reference.gtf I provided. (gene names are like chr1:266000)
(2) there is no "transcript" in the third columns, and "exon_number" are all zero.
(3) read names of output fa file don't match with the output gtf file. For example, the fasta file has some name originated from the reference gtf, such as "NM_004653_8284", but all transcript names of gtf file come from the input fastq and there is no NM_004653_8284. 

Are these valid results(There was no error message)? And if they are, could you help me on interpreting them and how to make connection between gtf and fasta output files? Thanks in advance.

-Yeji

**Comment by belgravia** [comment]
We've historically dealt with some issues regarding GTFs with slightly different formats, which then cause issues with flair-collapse/correct. 
(1) Could you send me a link to where you downloaded your reference.gtf from so I can take a look? And (2) if possible, could you also send some example flair isoforms where the gene name was unable to be found (i.e. chr1:266000)? It would be more helpful if you can find cases where the isoform called by flair looks like an annotated isoform/gene in your reference.gtf but doesn't get renamed properly.

The output fa and output gtf should match, so that may be an issue that I haven't run into yet and need to fix. 
-Alison

**Comment by yejilee-biostat** [comment]
Thank you, Alison.

(1) About the GTF file I used, It is downloaded from USCS Table browser (GRCh38, NCBI RefSeq Track) and modified a little bit, and looks like this:

> chr1    BestRefSeq      exon    11874   12227   .       +       .       transcript_id "NR_046018"; gene_id "100287102";
> chr1    BestRefSeq      exon    12613   12721   .       +       .       transcript_id "NR_046018"; gene_id "100287102";
> chr1    BestRefSeq      exon    13221   14409   .       +       .       transcript_id "NR_046018"; gene_id "100287102";

(2) I apologize that my previous explanation on this matter was not correct. It seems that read names on output fasta are changed, and now it has original reads name and gene names are connected by underscore, like:
>f9e9a133-3f5b-498f-80b0-2536be6fd87b_chr1:1613000
GGATTTTATTTTTCGTTTACacagggaatccaagaaaggagacagacaaagtgagtctcaaggatgagagcagagaaaagctcgagataagagctgtgcagccgggtcaggaagtgatcggtctaggtcggaacaggagaatcagttagacacaacggatgtgtttgagcctttggaaaacggtatcgttaggcatgtggcgaaaacgttggggtacttgaaaaaaaggctggccatgggttagtaaaaagctagatatgtg

and in the output gtf, it is recorded as:
> chr1    FLAIR   exon    1613773 1615773 .       -       1972    gene_id "chr1:1613000"; transcript_id "f9e9a133-3f5b-498f-80b0-2536be6fd87b"; exon_number "0";

Still, gene_id in the output gtf doesn't match with the one in the reference gtf(reference gtf does not have "chr" in it).  Also, it is not like FLAIR always put "chr" in gene_id of the output gtf. For example, some part of the output gtf looks like this:
>chr1    FLAIR   exon    23304724        23309778        .       -       5044    gene_id "chr1:23304000"; transcript_id "f617e82b-a84d-4755-86ad-27ffc87b0a09"; exon_number "0";
>chr1    FLAIR   exon    23369183        23371744        .       +       2562    gene_id "148898"; transcript_id "6ff5b0d8-661c-4589-9ca2-174c97ec9f0b"; exon_number "0";
>chr1    FLAIR   exon    23549182        23549705        .       -       524     gene_id "chr1:23549000"; transcript_id "18bce46b-a9e9-40b9-b693-717a8e6f927a"; exon_number "0";

Therefore, making the connection between the output fasta and gtf is still confusing.

(3) Also - It is what FLAIR intended when there is no "transcript" element in the third column of the output gtf and only "exon"s are there?

(4) Also - about some reads in the output fasta and but no information on gtf: 

> grep -A1 NM_004653_8284 flair.collapse.correct_w_ref.isoforms.fa
> NM_004653_8284
TCCAAACATACTCATTGTTTTATTTTTAACAAAAGAAATGAAATTAAAGATAGACCACAGGTAGAGTCATGAAATTCTTGTTTTTCCCTATTCTTTTTGGTAATTACAACGTACATTGTCTTCTTTTATAATAAGACCCAAGGGGAGAAAAGAAAAGGATGTACAATGAAGGTACAAGTTTTGAA...(it is from long read sequencing)

and 
>grep NM_004653_8284 flair.collapse.correct_w_ref.isoforms.gtf

returns nothing. How can I interpret this case?

English is not my first language - so please understand some grammatical errors and weird choices of words. Thanks a lot again.

**Comment by belgravia** [comment]
I will do my best to explain, and thank you for taking the time to describe your issue kindly to me in English :)

(1 & 2): Some of the confusion caused is inherent to the gtf file you are using. The transcript_id is `N*` and the gene_id is a number. 

The isoforms.fasta has headers that formatted are formatted like `transcriptid_geneid` and the isoforms.gtf has the transcript id and gene id separate. For example, if your transcript_id is `NR_046018` and your gene_id is `100287102`, then the isoform will be named `NR_046018_100287102` in your fasta/psl/bed file and it will be formatted `transcript_id "NR_046018"; gene_id "100287102"` in the flair gtf.

FLAIR gets the name of the transcript id and gene id by matching the flair isoforms with the reference isoforms. If a flair isoform does not match any reference isoform, then an arbitrary isoform name will be picked (e.g. a read id like f9e9a133-3f5b-498f-80b0-2536be6fd87b). If flair was not able to match the flair isoform to a reference gene, then an arbitrary gene name will be made (e.g. chromosome followed by the genomic coordinate, chr1:1613000). 

So if the gene field is just a number, then that number corresponds to the gene id in your gtf. If the gene field is `chr*:*`, then that isoform was not matched with an annotated gene in your reference file.

(3) That was a FLAIR error, I accidentally removed the transcript fields from the gtf. I have added it back in. If you run `bin/psl_to_gtf.py` on your isoform psl/bed file, or if you rerun flair-collapse, you should have both transcript and exon entries in your flair gtf.

(4) See 3, but please regenerate the flair gtf file. Also, based on what I mentioned in (1 & 2), you should grep for just `NM_004653` because `NM_004653_8284` contains both the transcript and gene id and in the gtf, the transcript and gene id are not connected with an underscore. 

Let me know how the new gtf looks.
-Alison

**Comment by yejilee-biostat** [comment]
Dear Alison,

 Thanks a lot again for more detailed explanation! I will update and run FLAIR again, and if there is no further issue, I will close this one.

-Yeji

**Comment by belgravia** [comment]
Hi Yeji,

Interesting, that was something that I had fixed in the psl_to_gtf.py script that I pushed yesterday.

If possible, could you send me the line with `NM_004653_8284` in the isoform psl/bed?

-Alison

**Comment by yejilee-biostat** [comment]
Hi Alison,
 Thanks for the quick reply again!

Strangely - there is no isoform named "NM004653" or  "NM_004653_8284" in the output psl/bed from FLAIR-correct,  (I didn't re-run this part, nor using psl_to_gtf.py separately. Also, when I ran FLAIR-collapse again yesterday, I just put the output psl file from FLAIR-collapse.).

The following is from the output psl file from FLAIR-collapse

>grep NM_004653 flair.collapse.correct_w_ref.isoforms.psl


> 5364    0       0       0       0       0       26      34037   -       NM_004653_8284  5364    0       5364    chrY    57227415        19705423        19744713        27      922,200,70,600,138,180,139,359,97,148,125,182,195,120,163,182,159,120,159,146,130,135,171,123,78,169,43,        0,930,1130,1200,1800,1938,2118,2257,2616,2713,2861,2986,3168,3363,3483,3646,3828,3987,4107,4266,4412,4542,4677,4848,4971,5049,5218,   19705423,19706440,19706793,19707146,19707933,19708243,19708874,19709450,19710375,19715351,19715614,19715822,19716278,19716595,19720871,19721129,19731771,19732045,19732583,19735351,19735620,19739527,19741317,19741734,19743161,19744384,19744670,

**Comment by belgravia** [comment]
The output isoforms.psl from collapse is what is used to make the isoforms.gtf. You only needed to rerun flair-collapse because that will run psl_to_gtf.py for you, so you are good.

I looked back at what I pushed yesterday and I just realized that I accidentally did not include the fix for the bug where the transcript ID NM_004653 is not properly separated from the gene ID 8284. Could you either rerun flair-collapse or just run psl_to_gtf.py on your isoforms.bed file? It should be fine now since I just updated the code.

-Alison

**Comment by yejilee-biostat** [comment]
Thanks a lot again, Alison! I have rerun flair-collapse and it seems everything looks fine now. I will close this issue.

-Yeji
