### ISSUE TITLE
flair-quantify misses some isoforms from flair-collapse 

### ISSUE THREAD

**Issue by yejilee-biostat** [BrooksLabUCSC/flair#77]
Dear Alison,

 Again, many thanks to all your previous quick replies. Can I ask for your help again?
 
 I have run flair-quantify for one sample with the results from flair-collapse. However, there are several isoforms from flair-collapse don't have isoform counts in the flair-quantify. For example, there is an isoform named "NM_002074_2782" in the output fasta and psl files from flair-collapse, but this isoform does not exist in the output tsv and tpm files from flair-quantify. Could you kindly explain what happens here? Thanks again.

-Yeji

**Comment by belgravia** [comment]
This can happen, typically with the more lowly expressed isoforms. In the collapse step, the supporting reads for each isoform are determined and isoforms that have too few supporting reads are removed. The removal of certain isoforms can change the way the reads are matched to isoforms, and this will cause some isoforms to have no supporting reads in the quantify step. You can try to avoid this from happening by increasing the stringency in the collapse step and decreasing the number of TSS/TES determined per splice junction chain to avoid ambiguity. In general, we are not too concerned with the isoforms that receive 0 supporting reads from flair-quantify and disregard them. I hope that helps.

**Comment by yejilee-biostat** [comment]
Dear Alison,

 Thanks for the kind explanation again! I will close this issue.

**Comment by ryanpe13002** [comment]
Hi all, just reopening this to clarify - if flair-quantify does not output an isoform from the input BED file in the output files (count and TPM), that means that the isoform was assigned zero counts across all samples, correct?

For clarification, we used long read sequencing data from PacBio with an in-house processing pipeline to generate a GTF that we then use flair-quantify to estimate isoform abundance from the original long-read sequencing FASTA files. However, not all isoforms are listed in the flair-quantify output files. We presume this is because they received 0 counts in all samples, but wish to confirm this.

Thanks so much!
