### ISSUE TITLE
flair correct with -j parameter

### ISSUE THREAD

**Issue by DelphIONe** [BrooksLabUCSC/flair#81]
Hi,

I have one problem with this module. It works very well with -g option but wtih -j (file from STAR mapping), I have this error :

python ~/softs/flair/flair.py correct -q BC07.bed -g Dp71_mm10_Genomic_UpperCaseOnly.fasta -j star_out/SJ_sup100.out.tab --print_check
Step 2/5: Processing additional junction file  star_out/SJ_sup100.out.tab ...too many values to unpack Splice site motif filtering failed. Check pybedtools and bedtools is properly install and in $PATH
Correction command did not exit with success status

Correspondance between chromosome name in different file is ok. Bedtools and pybedtools are ok too/ So, can you help me please ?

Thanks,

**Comment by belgravia** [comment]
Hi,

Can you send a line of your star junctions.tab file? I am wondering if that somehow has more columns than the code is anticipating.

The error message formatting looks more like it could be a bedtools/pybedtools versioning issue. What version of bedtools and pybedtools are you using?

-Alison

**Comment by DelphIONe** [comment]
Thanks for your reply.
I have installed flair in conda environnement and it's ok for this point. But I have now an other problem. Maybe easy for you ?
In module correct, with -f option only, no error and I obtain these files
-rw-r--r-- 1 w tous 121168954 nov.  26 11:13 BC07_all_corrected.bed
-rw-r--r-- 1 w tous  25647074 nov.  26 11:13 BC07_all_inconsistent.bed

With both, -j and -f I obtain 
Step 2/5: Processing additional junction file  ../SJ_sup100.out.tab ...WARNING. chromosome (MM10_KNOWNGENE_x) was not found in the FASTA file. Skipping.█| 1/1 [00:00<00:00, 7231.56it/s]
WARNING. chromosome (MM10_KNOWNGENE_x) was not found in the FASTA file. Skipping.
...
repeated 10 times
...
Step 5/5: Correcting Splice Sites: 100%|█| 1/1 [00:54<00:00, 54.63s/it]

despite of that, I obtain these files 
-rw-r--r-- 1 w tous 121168954 nov.  26 11:10 BC07_all_corrected.bed
-rw-r--r-- 1 w tous  25647074 nov.  26 11:10 BC07_all_inconsistent.bed

=> exactly the same size that before only the -j option, is it normal ? The output is exploitable even if these errors display ?

Lastly, with only -j option (without -f), I obtain
Step 2/5: Processing additional junction file  ../SJ_sup100.out.tab ...WARNING. chromosome (MM10_KNOWNGENE_x) was not found in the FASTA file. Skipping.
WARNING. chromosome (MM10_KNOWNGENE_x) was not found in the FASTA file. Skipping.
...
repeated 26 times
...
Step 5/5: Correcting Splice Sites: 100%|█| 1/1 [00:52<00:00, 52.73s/it]

And I obtain these files
-rw-r--r-- 1 w tous    106556 nov.  26 11:15 BC07_all_corrected.bed
-rw-r--r-- 1 w tous 146801688 nov.  26 11:15 BC07_all_inconsistent.bed

which have different sizes. Why the warning display number is different ? It's the same file.

I can understand if the "new illumina junction" are already in gtf file that the output with -f only or with both -f and -j are the same but I would like to be sure. The warning worried me.

Thanks for your help,

**Comment by belgravia** [comment]
Those warnings are ok.

Flair-correct will take the introns specified in your gtf and/or the short read junction files and then compare those introns to all the introns in the long reads. The reads that contain introns that match the .gtf/.tab introns within a wiggle room are put in the *corrected.bed, and the reads that contain 1+ intron that is _not_ in the .gtf/.tab file(s) are put in the *inconsistent.bed. The last case, where you only use the .tab file to correct, there are not many introns in the .tab file that are useful for correcting the long reads, so most reads are unable to be corrected (larger proportion put in *inconsistent.bed.

Your detailed report tells me that 
1) your star junction file contains a chromosome called MM10_KNOWNGENE_x and this chromosome is not present in your genome fasta file. 
2) your short read junctions are not adding any meaningful introns for flair-correct to correct the reads with, because the sizes of the output files did not change at all adding -j

Hope this helps.
-Alison

**Comment by DelphIONe** [comment]
Hi Alison,

I understand those warnings but it's not true. I have only one sequence in my fasta file :
 grep ">" ../../MM10_KNOWNGENE_x.fasta
>MM10_KNOWNGENE_x

What is the problem ?
Thanks,

**Comment by belgravia** [comment]
What is the fasta file you are giving to flair align/correct?
It should be the genome sequence, not the sequence of your targeted transcript.

For the reads that are in the *corrected.bed files, I would assume none of them are on chromosome 'MM10_KNOWNGENE_x', right?

-Alison

**Comment by DelphIONe** [comment]
The fasta file is MM10_KNOWNGENE_x.fasta with the sequence named >MM10_KNOWNGENE_x
I thought that my first errors were because of different names bewtween file name and sequence so, I have modified the entry name. But it's ok, it's the genome sequence, not the transcript sequence of course.

An example of my *_corrected.bed files : 
MM10_KNOWNGENE_x     0       5607    7230edb7-f851-4af4-aa9f-cf08ce07feb9;0  4       +       0       5607    27,158,119      2       47,49,  0,5558,
MM10_KNOWNGENE_x    0       104704  0ce823f6-97a1-4b3c-ba20-ff9366bfd73e;0  60      +       0       104704  27,158,119      12      47,62,75,202,86,158,167,112,137,66,66,90,       0,5558,41404,56731,59167,61530,90915,93313,95616,100717,101800,104614,
...

The chromosome MM10_KNOWNGENE_x is really present.

**Comment by csoulette** [comment]
Hi DelphION,

Can you clarify what your input arguments are? In the first example you mention that you've ran this command:

> `python ~/softs/flair/flair.py correct -q BC07.bed -g Dp71_mm10_Genomic_UpperCaseOnly.fasta -j star_out/SJ_sup100.out.tab --print_check`

Where `Dp71_mm10_Genomic_UpperCaseOnly.fasta` is your input genomic fasta.

However, when you ran grep to show that MM10_KNOWNGENE_x is in your fasta, you ran grep on a different fasta file:

>`grep ">" ../../MM10_KNOWNGENE_x.fasta`

I just want to confirm that you are running `correct` using Dp71_mm10_Genomic_UpperCaseOnly.fasta, which contains MM10_KNOWNGENE_x. Also, if you've added MM10_KNOWNGENE_x to Dp71_mm10_Genomic_UpperCaseOnly.fasta then it is important that the pybedtools index created  for Dp71_mm10_Genomic_UpperCaseOnly.fasta was done so after you added MM10_KNOWNGENE_x.

Thanks~

-CMS

**Comment by DelphIONe** [comment]
Yes, I have removed Dp71_mm10_Genomic_UpperCaseOnly.fasta and I have deleted the index too. I thought that maybe, the name file could be the cause of problem. But not.

**Comment by csoulette** [comment]
Hi @DelphIONe ,

I'm trying to recapitulate your issue here, could you share the version of `pybedtools getfasta` you are using? There may be formatting issued between bedtools versions. Could you try updating bedtools to at least version  v2.28 or v2.29.

Also, I just want to confirm that the genome fasta file you are using for flair-correct is the same one that you used for the short-read STAR alignment and flair-align steps?

Thanks~

-CMS

**Comment by DelphIONe** [comment]
Hi,

The genome fasta file is the same one between STAR and Flair.
With the new bedtools version, it seems ok.

Thanks,
