### ISSUE TITLE
Normalization before or during FLAIR modules

### ISSUE THREAD

**Issue by drc111** [BrooksLabUCSC/flair#83]
Dear FLAIR developers,

I have not been able to find out whether you do any read/library normalization prior to running FLAIR or whether this is done during some of the FLAIR modules/scripts. 

I can see in /bin that you have a ‘normalize_counts_matrix.py’ script, but I cannot see that it is used in flair.py, deFLAIR.py, or runDE.py. 

I would appreciate if you could elaborate a bit on this please!

Best,
Sebastian

**Comment by belgravia** [comment]
Hi Sebastion,

That's correct, the flair-quantify output is not normalized by read or library depth. I haven't yet put an option in flair-quantify to output the normalized matrix for users but since this may be of interest to many users, I will add it in to flair-quantify in the next update.

Since I presume you already have run flair-quantify, you can run normalize_counts_matrix.py with the following syntax:
`python normalize_counts_matrix.py counts_matrix.tsv output_counts_matrix.tsv` where counts_matrix.tsv is your flair-quantify output and the output_counts_matrix.tsv is just the name of your output file. You can add an optional third argument to specify the normalization method. By default it is 'cpm' for counts per million reads, but you could also use 'uq' for upper-quarter normalization or 'median' for normalizing with the median count for each sample.

Hope that helps!

-Alison

**Comment by drc111** [comment]
Dear Alison,

Thanks for your quick reply, that would be really helpful! 

Also as a completely different side note, I tried to pull the flair docker image today but I was unable to run flair since many of the required packages were missing/not installed. Are you currently doing an update or do you have any idea why the packages were not installed? No error was given.

Best,
Sebastian

**Comment by csoulette** [comment]
Hi Sebastian,

I just wanted to chime in about FLAIR-diffExp since you mentioned deFLAIR.py and runDE.py.

For the FLAIR-diffExp module, it is essentially a convenience wrapper for DESeq2 and DRIMSeq. These two algorithms use a statistical approach to measure the expression variability between biological replicates, and will adjust expression counts accordingly. Moreover, the required input to these two algorithms are raw counts, and so FLAIR-diffExp will operate on the raw counts table produced by FLAIR-quantify.

Best,
CMS

**Comment by belgravia** [comment]
Yes we may have added more dependencies since we made the docker.

For now, if you are not tied to using the docker, you could use the conda environment (described in the readme) or package (described in issue #37) we have.

-Alison

**Comment by drc111** [comment]
Hi Alison and Cameron,

Right, so that means the input to FLAIR-diffExp should be the un-normalized counts produced by FLAIR-quantify, and then DESeq2 and DRIMSeq normalize/adjust the expression counts for their individual analyses? 

Since you mentioned FLAIR-quantify, I have also noticed that you have changed the FLAIR-quantify ‘--quality’ flag default setting from 0 to 1 over the last months assumingly to remove multi-mapped reads – is that for better adaption to native RNA seq reads (e.g. by removing reads from rRNA)?

Thanks for your time!

Best,
Sebastian

**Comment by belgravia** [comment]
Hi Sebastian,

Yes to your first question, as Cameron clarified.

For the second question, I had been running the quantify with a minimum quality of 1 for a while and since it was what we found performed best in our flair sf3b1 paper, I finally switched the default from 0 to 1 for all users. Yes, it's to remove multimappers. It's not specifically for native RNA sequencing or rRNA reads; it's just a measure to remove truncated reads that align ambiguously to multiple isoforms. Related to this, I made a preset (`--trust_ends`) for libraries that don't suffer from as much truncation (e.g. pacbio and R2C2 right?) to consider the mapq 0 reads within reason. Hope this helps.

-Alison
