### ISSUE TITLE
diff_iso_usage.py drops isoforms with a count of 0.0

### ISSUE THREAD

**Issue by yoon5812** [BrooksLabUCSC/flair#91]
Hi Alison, 

Thank you for developing a great tool.

I used diff_iso_usage.py to analyze isoform usage between two samples. 
When I checked the result file, I found that isoforms with 0 counts were dropped.

For example:

`404c812d-700a-42c3-9d1c-1c5e3c2a8114_ENSG00000008394  7.063   0.0
`

The isoform shown above has 0 count in the second sample. This form was not found in the output of diff_iso_usage.py. 

I guess its because of this line (line number 39-40):

```
        if count1 != 0 and count2 != 0:
                counts[gene][iso] = [count1, count2]
```

But I think this isoform is more important because it is found only in one sample.

When I changed the code to this ('and' to 'or'):

```
        if count1 != 0 or count2 != 0:
                counts[gene][iso] = [count1, count2]
```

The results looked good. This will drop isoforms when they have 0 count in both samples. Is this okay?

Thank you.
Yoon

**Comment by belgravia** [comment]
Yes, I think that is fine as long as you make a note of this. Performing more fisher's tests will affect your adjusted pvalues. The reason we had removed cases with 0 counts was because we were worried about letting in too much noise.

I wrote a response for this last week, but I guess I forgot to send it. Thanks for your patience!

-Alison
