### ISSUE TITLE
Flair quantify missing counts for one isoform

### ISSUE THREAD

**Issue by wigge206** [BrooksLabUCSC/flair#94]
When I run flair quantify, I get counts for all but one of my isoforms that are produced by flair collapse. The id for the isoform is in the fa file that I pass into.
Is there any reason why this might occur?

**Comment by belgravia** [comment]
Yes, I answered this in #77. I hope the answer is sufficient. Please let me know if you have further questions!

**Comment by wigge206** [comment]
Thank you for that, sorry I missed that thread. To clarify, it is possible to have an evidence for an isoform after collapse but due to removal of reads (not associated with the isofrom), when the quantify step is preformed some of the reads that were supporting your isoform may no longer?

**Comment by wigge206** [comment]
Sorry I missed that, it is cruious th

**Comment by belgravia** [comment]
I'll try to clarify this:
In the collapse step, FLAIR takes all of your reads from all samples and assigns them to first-pass isoforms that they match best. The first-pass isoforms that have `-s` supporting reads or more are kept in the high-confidence `*isoforms.gtf`. In the quantify step, FLAIR again takes all of your reads from each sample individually and assigns them to the best-match high-confidence isoform.

The step of assigning a read to an isoform used in both collapse/quantify can sometimes be ambiguous. By default, this step is accomplished by using minimap2 to align the reads to the isoform sequences, and then determining which isoform it aligned best to. The best alignment is the one that has the highest MAPQ score. So FLAIR does discard reads where all the isoform alignments for that read have the lowest quality score of 0, since these are ambiguous and lower quality. However, there are still reads that may align well to multiple isoforms that may pass through this filter. We have observed that minimap2 does not always align ambiguous reads in a consistent manner in terms of the MAPQ that are assigned and which isoform is the primary alignment. The ambiguity means that there are a subset of the reads that may be assigned to one isoform in the collapse step, and then a different one in the quantify step, resulting in the removal of the isoforms that don't have any reads assigned to them. Ambiguous reads are dealt with differently if you run with the `--trust_ends` mode, or `--salmon`.

So it's not quite a removal of reads, but instead subtle changes in how the reads were assigned to the isoforms that mainly affects the isoforms that are lowly expressed. You should be able to mitigate this behavior by specifying a higher --quality score in the collapse and quantify steps. 
Thanks for your patience, hope this helps.
-Alison
